Update angular-ci.yml
test

diff --git a/.github/workflows/angular-ci.yml b/.github/workflows/angular-ci.yml
--- a/.github/workflows/angular-ci.yml
+++ b/.github/workflows/angular-ci.yml
@@ -36,3 +36,12 @@ jobs:
 
     - name: Test
       run: npm run test-headless
+      
+    - name: Greeting
+      run: echo "Hello, world!"
+
+    - name: Simulate an error
+      run: echo "About to fail" ; exit 1
+
+    - name: Another greeting
+      run: echo "Hello, world!"
